language: php
php:
  - '7.2'
services:
  - mysql

services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
before_script:
  - composer install
  - mv tests/test_env .env
  - mysql -e 'CREATE DATABASE shortycli;'
  - php artisan migrate --force
  - composer install
notifications:
  email: false